# Generated by Django 5.2.6 on 2025-10-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='image',
            field=models.ImageField(default='movie-cover/default.jpg', upload_to='movie-cover'),
        ),
    ]
